################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
BSP/MSP430F5xx_6xx/adc10_a.obj: ../BSP/MSP430F5xx_6xx/adc10_a.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/adc10_a.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/adc12_a.obj: ../BSP/MSP430F5xx_6xx/adc12_a.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/adc12_a.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/aes.obj: ../BSP/MSP430F5xx_6xx/aes.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/aes.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/battbak.obj: ../BSP/MSP430F5xx_6xx/battbak.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/battbak.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/comp_b.obj: ../BSP/MSP430F5xx_6xx/comp_b.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/comp_b.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/crc.obj: ../BSP/MSP430F5xx_6xx/crc.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/crc.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/ctsd16.obj: ../BSP/MSP430F5xx_6xx/ctsd16.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/ctsd16.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/dac12_a.obj: ../BSP/MSP430F5xx_6xx/dac12_a.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/dac12_a.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/dma.obj: ../BSP/MSP430F5xx_6xx/dma.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/dma.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/eusci_a_spi.obj: ../BSP/MSP430F5xx_6xx/eusci_a_spi.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/eusci_a_spi.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/eusci_a_uart.obj: ../BSP/MSP430F5xx_6xx/eusci_a_uart.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/eusci_a_uart.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/eusci_b_i2c.obj: ../BSP/MSP430F5xx_6xx/eusci_b_i2c.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/eusci_b_i2c.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/eusci_b_spi.obj: ../BSP/MSP430F5xx_6xx/eusci_b_spi.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/eusci_b_spi.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/flashctl.obj: ../BSP/MSP430F5xx_6xx/flashctl.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/flashctl.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/gpio.obj: ../BSP/MSP430F5xx_6xx/gpio.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/gpio.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/lcd_b.obj: ../BSP/MSP430F5xx_6xx/lcd_b.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/lcd_b.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/ldopwr.obj: ../BSP/MSP430F5xx_6xx/ldopwr.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/ldopwr.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/mpy32.obj: ../BSP/MSP430F5xx_6xx/mpy32.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/mpy32.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/oa.obj: ../BSP/MSP430F5xx_6xx/oa.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/oa.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/pmap.obj: ../BSP/MSP430F5xx_6xx/pmap.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/pmap.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/pmm.obj: ../BSP/MSP430F5xx_6xx/pmm.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/pmm.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/ram.obj: ../BSP/MSP430F5xx_6xx/ram.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/ram.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/ref.obj: ../BSP/MSP430F5xx_6xx/ref.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/ref.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/rtc_a.obj: ../BSP/MSP430F5xx_6xx/rtc_a.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/rtc_a.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/rtc_b.obj: ../BSP/MSP430F5xx_6xx/rtc_b.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/rtc_b.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/rtc_c.obj: ../BSP/MSP430F5xx_6xx/rtc_c.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/rtc_c.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/sd24_b.obj: ../BSP/MSP430F5xx_6xx/sd24_b.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/sd24_b.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/sfr.obj: ../BSP/MSP430F5xx_6xx/sfr.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/sfr.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/sysctl.obj: ../BSP/MSP430F5xx_6xx/sysctl.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/sysctl.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/tec.obj: ../BSP/MSP430F5xx_6xx/tec.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/tec.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/timer_a.obj: ../BSP/MSP430F5xx_6xx/timer_a.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/timer_a.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/timer_b.obj: ../BSP/MSP430F5xx_6xx/timer_b.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/timer_b.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/timer_d.obj: ../BSP/MSP430F5xx_6xx/timer_d.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/timer_d.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/tlv.obj: ../BSP/MSP430F5xx_6xx/tlv.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/tlv.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/ucs.obj: ../BSP/MSP430F5xx_6xx/ucs.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/ucs.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/usci_a_spi.obj: ../BSP/MSP430F5xx_6xx/usci_a_spi.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/usci_a_spi.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/usci_a_uart.obj: ../BSP/MSP430F5xx_6xx/usci_a_uart.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/usci_a_uart.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/usci_b_i2c.obj: ../BSP/MSP430F5xx_6xx/usci_b_i2c.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/usci_b_i2c.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/usci_b_spi.obj: ../BSP/MSP430F5xx_6xx/usci_b_spi.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/usci_b_spi.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

BSP/MSP430F5xx_6xx/wdt_a.obj: ../BSP/MSP430F5xx_6xx/wdt_a.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/bin/cl430" -vmspx --abi=eabi --data_model=restricted --use_hw_mpy=F5 --include_path="G:/DeveloperFiles/ti/ccsv6/ccs_base/msp430/include" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/cJSON" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Platform" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/utils" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/FatFs" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Devicelib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP/Hallib" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/App" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-CPU/MSP430/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uC-LIB" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Ports/MSP430X/CCS" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/uCOS-II/Source" --include_path="G:/04  MyDesign/04  CCS/glz_msp430_ucOS_II/BSP" --include_path="G:/DeveloperFiles/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include" --advice:power=all -g --define=__MSP430F5259__ --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU21 --silicon_errata=CPU22 --silicon_errata=CPU40 --printf_support=full --preproc_with_compile --preproc_dependency="BSP/MSP430F5xx_6xx/wdt_a.pp" --obj_directory="BSP/MSP430F5xx_6xx" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


